steps:
  - name: 'golang:1.26' # Goのバージョンを1.21に合わせる
    entrypoint: 'go'
    args: ['build', '-o', 'app', './cmd/autoscaler']
    env: []
  - name: 'gcr.io/kaniko-project/executor:v1.9.1'
    args:
      - --destination=asia-northeast1-docker.pkg.dev/$PROJECT_ID/autoscaler/main:$BRANCH_NAME
      - --destination=asia-northeast1-docker.pkg.dev/$PROJECT_ID/autoscaler/main:$COMMIT_SHA
      - --cache=true
      - --cache-ttl=6h